Part7
MasonSelf/PFMCPP_Project4 pull request #8
Opened 2020-12-17 22:16 UTC by MasonSelf

2020-12-17 22:25 UTC, matkatmusic requested changes

2020-12-17 22:25 UTC, matkatmusic commented on main.cpp
> +        }
Fix this indentation
- [ ] revise

2020-12-17 22:25 UTC, matkatmusic commented on main.cpp
> +            else if ( mod <  std::numeric_limits<Type>::epsilon())
This should be `<DivType>` not `<Type>`
you're comparing if your parameter is less than its type's epsilon, not your class type's epsilon.
Also, if `Type` has an epsilon of 0.f, and `mod` is -1.f, will this `if()` block be entered?
- [ ] revise

2020-12-17 22:25 UTC, matkatmusic commented on main.cpp
> +        return *this;
Fix this indentation

- [ ] revise

2020-12-18 05:22 UTC, matkatmusic requested changes

2020-12-18 05:22 UTC, matkatmusic commented on main.cpp
> +            else if ( mod <  std::numeric_limits<DivType>::epsilon())
This doesn't answer my question about: if the `epsilon` of `DivType` is `0.f`, and `mod is `-1.f`, is this `if` block entered?  and if it is, is the `std::cout` statement correct?
- [ ] revise

2020-12-18 05:22 UTC, matkatmusic commented on main.cpp
> +                else if ( mod <  std::numeric_limits<DivType>::epsilon())
This doesn't answer my question about: if the `epsilon` of `DivType` is `0.f`, and `mod is `-1.f`, is this `if` block entered?  and if it is, is the `std::cout` statement correct?
- [ ] revise

2020-12-18 20:12 UTC, MasonSelf commented on main.cpp
> +            else if ( mod <  std::numeric_limits<DivType>::epsilon())
abs will account for that

2020-12-18 20:12 UTC, MasonSelf commented on main.cpp
> +                else if ( mod <  std::numeric_limits<DivType>::epsilon())
abs will account for that

2020-12-18 21:32 UTC, matkatmusic approved these changes

2020-12-18 21:33 UTC, merged